name: docker-build-cloud

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: ${{ secrets.BUILDCLOUD_ENDPOINT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          sbom: true
          platforms: linux/amd64,linux/arm64
          context: .
          tags: ${{ vars.DOCKERHUB_IMAGE_TAG }}
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
  
